import 'dart:convert';

import 'package:sqflite/sqflite.dart';
import 'package:uuid/uuid.dart';

import '../../core/constants.dart';
import '../models/bank.dart';
import '../models/change_log.dart';
import '../models/counter_entity.dart';
import '../models/material_item.dart';
import '../models/material_type_def.dart';
import '../models/party.dart';
import '../models/project.dart';

const _uuid = Uuid();

/// Sentinel for "argument not supplied" so update methods can distinguish
/// "leave this column alone" from "set this column to NULL". Use
/// `identical(arg, _unset)` to test — never `==`, since `==` on Object
/// could match other instances.
const Object _unset = Object();

class EntityRepository {
  EntityRepository(this._db);
  final Database _db;

  /// Cached device_id, fetched lazily from `app_settings` and reused for every
  /// audit write. The value is generated by `BackupService.ensureDeviceId` on first run.
  String? _cachedDeviceId;
  Future<String?> _deviceId() async {
    if (_cachedDeviceId != null) return _cachedDeviceId;
    final v = await getSetting('device_id');
    _cachedDeviceId = v;
    return v;
  }

  // ---- Projects ----

  Future<Project> createProject({
    required String name,
    required ProjectModel model,
    String? clientName,
    String? siteAddress,
    double? budget,
    String? projectManager,
    double? serviceFeePercent,
  }) async {
    final p = Project(
      id: _uuid.v4(),
      name: name.trim(),
      model: model,
      status: ProjectStatus.active,
      createdAt: DateTime.now().toUtc(),
      clientName:
          clientName?.trim().isEmpty == true ? null : clientName?.trim(),
      siteAddress:
          siteAddress?.trim().isEmpty == true ? null : siteAddress?.trim(),
      budget: budget,
      projectManager:
          projectManager?.trim().isEmpty == true ? null : projectManager?.trim(),
      serviceFeePercent: serviceFeePercent,
    );
    await _db.insert('projects', p.toMap());
    return p;
  }

  Future<void> updateProjectFields(
    String id, {
    String? name,
    String? clientName,
    String? siteAddress,
    double? budget,
    String? projectManager,
    double? serviceFeePercent,
  }) async {
    final updates = <String, Object?>{};
    if (name != null) updates['name'] = name.trim();
    if (clientName != null) {
      updates['client_name'] = clientName.trim().isEmpty ? null : clientName.trim();
    }
    if (siteAddress != null) {
      updates['site_address'] = siteAddress.trim().isEmpty ? null : siteAddress.trim();
    }
    if (budget != null) updates['budget'] = budget;
    if (projectManager != null) {
      updates['project_manager'] =
          projectManager.trim().isEmpty ? null : projectManager.trim();
    }
    if (serviceFeePercent != null) {
      updates['service_fee_percent'] = serviceFeePercent;
    }
    if (updates.isEmpty) return;
    await _db.update('projects', updates, where: 'id = ?', whereArgs: [id]);
  }

  Future<List<Project>> projects(
      {bool activeOnly = false, bool includeArchived = false}) async {
    final clauses = <String>[];
    final args = <Object>[];
    if (activeOnly) {
      clauses.add('status = ?');
      args.add(ProjectStatus.active.db);
    }
    if (!includeArchived) {
      clauses.add('is_archived = 0');
    }
    final rows = await _db.query(
      'projects',
      where: clauses.isEmpty ? null : clauses.join(' AND '),
      whereArgs: clauses.isEmpty ? null : args,
      orderBy: 'created_at DESC',
    );
    return rows.map(Project.fromMap).toList();
  }

  Future<List<Project>> archivedProjects() async {
    final rows = await _db.query(
      'projects',
      where: 'is_archived = 1',
      orderBy: 'archived_at DESC',
    );
    return rows.map(Project.fromMap).toList();
  }

  Future<Project?> project(String id) async {
    final rows = await _db.query('projects', where: 'id = ?', whereArgs: [id]);
    return rows.isEmpty ? null : Project.fromMap(rows.first);
  }

  Future<void> updateProjectStatus(String id, ProjectStatus status) async {
    await _db.update('projects', {'status': status.db},
        where: 'id = ?', whereArgs: [id]);
  }

  Future<void> updateProjectServiceFee(String id, double? percent) async {
    await _db.update('projects', {'service_fee_percent': percent},
        where: 'id = ?', whereArgs: [id]);
  }

  /// Soft-archive: preserves data, removes from active lists. Logged.
  ///
  /// **All projects are gated** by the project ledger balance: every cost
  /// posted against the project must be cancelled by an equivalent inflow
  /// (project revenue + service-fee income) before the project can be
  /// archived. Suppliers tied to the project must also be settled
  /// (no outstanding payable). For Labour-Rate projects, the
  /// reconciliation screen posts the service-fee reclassification first;
  /// the user then has to record the refund or collection so the ledger
  /// nets to zero.
  ///
  /// Throws [ReconciliationException] when the gate fails.
  ///
  /// Pass `force: true` to bypass the gate — only used for migrations or
  /// data-repair flows.
  Future<void> archiveProject(String id,
      {String? note, bool force = false}) async {
    final p = await project(id);
    if (p == null) return;

    if (!force) {
      final balance = await _projectLedgerBalance(id);
      if (balance.isOutOfBalance) {
        throw ReconciliationException(
          projectId: id,
          outstandingPayables: balance.supplierPayables,
          netLedger: balance.ledgerNet,
        );
      }
    }

    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'projects',
        {'is_archived': 1, 'archived_at': now.toIso8601String()},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'project',
            entityId: id,
            action: ChangeAction.archive,
            originalData: jsonEncode(p.toMap()),
            note: note,
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  /// Computes both gates that have to be satisfied before a project can be
  /// archived:
  ///
  ///   * `supplierPayables` — outstanding credit balance of
  ///     `Supplier Payables` for this project. Must be 0 (every credited
  ///     bill paid down).
  ///   * `ledgerNet` — net of the project ledger as the user sees it on
  ///     the Project Ledger screen: cost-side debits (Material, Labour)
  ///     minus credit-side income (Project Revenue, Service Fee Income).
  ///     Must be 0 — every rupee charged to the project has to be
  ///     cancelled by an inflow before archive.
  Future<_ProjectLedgerBalance> _projectLedgerBalance(String projectId) async {
    Future<double> sum(String column, String accountId) async {
      final rows = await _db.rawQuery(
        'SELECT COALESCE(SUM($column),0) AS s FROM journal_entries '
        'WHERE account_id = ? AND project_id = ? AND is_deleted = 0',
        [accountId, projectId],
      );
      return ((rows.first['s'] as num?) ?? 0).toDouble();
    }

    final supplierPaid = await sum('debit', Accounts.supplierPayables.id);
    final supplierCredits = await sum('credit', Accounts.supplierPayables.id);
    final supplierPayables = supplierCredits - supplierPaid;

    final materialDr = await sum('debit', Accounts.materialCosts.id);
    final labourDr = await sum('debit', Accounts.labourCosts.id);
    final revenueCr = await sum('credit', Accounts.projectRevenue.id);
    final feeCr = await sum('credit', Accounts.serviceFeeIncome.id);
    // Same convention as the project ledger view: debits push the running
    // total positive (cost incurred), credits pull it negative (income
    // booked). Zero means everything spent has been paid for.
    final ledgerNet =
        (materialDr + labourDr) - (revenueCr + feeCr);

    return _ProjectLedgerBalance(
      supplierPayables: supplierPayables,
      ledgerNet: ledgerNet,
    );
  }

  Future<void> unarchiveProject(String id) async {
    final p = await project(id);
    if (p == null) return;
    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'projects',
        {'is_archived': 0, 'archived_at': null},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'project',
            entityId: id,
            action: ChangeAction.unarchive,
            originalData: jsonEncode(p.toMap()),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  // ---- Suppliers ----

  Future<Party> createSupplier({
    required String name,
    String? phone,
    SupplierCategory? category,
    String? taxStatus,
    String? bankDetails,
  }) async {
    final p = Party(
      id: _uuid.v4(),
      name: name.trim(),
      phone: phone?.trim().isEmpty == true ? null : phone?.trim(),
      createdAt: DateTime.now().toUtc(),
      category: category,
      taxStatus: taxStatus?.trim().isEmpty == true ? null : taxStatus?.trim(),
      bankDetails:
          bankDetails?.trim().isEmpty == true ? null : bankDetails?.trim(),
    );
    await _db.insert('suppliers', p.toSupplierMap());
    return p;
  }

  Future<List<Party>> suppliers({bool includeArchived = false}) async {
    final rows = await _db.query(
      'suppliers',
      where: includeArchived ? null : 'is_archived = 0',
      orderBy: 'name COLLATE NOCASE',
    );
    return rows.map(Party.fromMap).toList();
  }

  Future<List<Party>> archivedSuppliers() async {
    final rows = await _db.query(
      'suppliers',
      where: 'is_archived = 1',
      orderBy: 'archived_at DESC',
    );
    return rows.map(Party.fromMap).toList();
  }

  Future<Party?> supplier(String id) async {
    final rows =
        await _db.query('suppliers', where: 'id = ?', whereArgs: [id]);
    return rows.isEmpty ? null : Party.fromMap(rows.first);
  }

  Future<void> updateSupplierFields(
    String id, {
    String? name,
    String? phone,
    SupplierCategory? category,
    String? taxStatus,
    String? bankDetails,
  }) async {
    final updates = <String, Object?>{};
    if (name != null) updates['name'] = name.trim();
    if (phone != null) {
      updates['phone'] = phone.trim().isEmpty ? null : phone.trim();
    }
    if (category != null) updates['category'] = category.db;
    if (taxStatus != null) {
      updates['tax_status'] =
          taxStatus.trim().isEmpty ? null : taxStatus.trim();
    }
    if (bankDetails != null) {
      updates['bank_details'] =
          bankDetails.trim().isEmpty ? null : bankDetails.trim();
    }
    if (updates.isEmpty) return;

    final before = await supplier(id);
    if (before == null) return;
    final dev = await _deviceId();
    final now = DateTime.now().toUtc();
    await _db.transaction((txn) async {
      await txn.update('suppliers', updates,
          where: 'id = ?', whereArgs: [id]);
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'supplier',
            entityId: id,
            action: ChangeAction.edit,
            originalData: jsonEncode(before.toSupplierMap()),
            newData: jsonEncode(updates),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  /// Archives a supplier (material or labour). Gated on a zero payable
  /// balance so the user can't lose track of money still owed in either
  /// direction. Throws [SupplierNotSettledException] when the balance is
  /// non-zero. Pass `force: true` to bypass (migrations / data repair).
  Future<void> archiveSupplier(String id,
      {String? note, bool force = false}) async {
    final p = await supplier(id);
    if (p == null) return;

    if (!force) {
      final balance = await _supplierPayableBalance(id);
      if (balance.abs() >= 0.01) {
        throw SupplierNotSettledException(
          supplierId: id,
          outstandingBalance: balance,
        );
      }
    }

    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'suppliers',
        {'is_archived': 1, 'archived_at': now.toIso8601String()},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'supplier',
            entityId: id,
            action: ChangeAction.archive,
            originalData: jsonEncode(p.toSupplierMap()),
            note: note,
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  /// Net Supplier Payables for one supplier, in the credit-natural
  /// direction (positive = we owe them, negative = they owe us).
  Future<double> _supplierPayableBalance(String supplierId) async {
    final rows = await _db.rawQuery(
      'SELECT COALESCE(SUM(credit),0) - COALESCE(SUM(debit),0) AS bal '
      'FROM journal_entries '
      'WHERE account_id = ? AND supplier_id = ? AND is_deleted = 0',
      [Accounts.supplierPayables.id, supplierId],
    );
    return ((rows.first['bal'] as num?) ?? 0).toDouble();
  }

  Future<void> unarchiveSupplier(String id) async {
    final p = await supplier(id);
    if (p == null) return;
    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'suppliers',
        {'is_archived': 0, 'archived_at': null},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'supplier',
            entityId: id,
            action: ChangeAction.unarchive,
            originalData: jsonEncode(p.toSupplierMap()),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  // ---- Banks ----

  Future<Bank> createBank({required String name, String? accountNo}) async {
    final b = Bank(
      id: _uuid.v4(),
      name: name.trim(),
      accountNo: accountNo?.trim().isEmpty == true ? null : accountNo?.trim(),
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('banks', b.toMap());
    return b;
  }

  Future<List<Bank>> banks({bool includeArchived = false}) async {
    final rows = await _db.query(
      'banks',
      where: includeArchived ? null : 'is_archived = 0',
      orderBy: 'name COLLATE NOCASE',
    );
    return rows.map(Bank.fromMap).toList();
  }

  Future<List<Bank>> archivedBanks() async {
    final rows = await _db.query(
      'banks',
      where: 'is_archived = 1',
      orderBy: 'archived_at DESC',
    );
    return rows.map(Bank.fromMap).toList();
  }

  Future<Bank?> bank(String id) async {
    final rows = await _db.query('banks', where: 'id = ?', whereArgs: [id]);
    return rows.isEmpty ? null : Bank.fromMap(rows.first);
  }

  Future<void> updateBankFields(
    String id, {
    String? name,
    String? accountNo,
  }) async {
    final updates = <String, Object?>{};
    if (name != null) updates['name'] = name.trim();
    if (accountNo != null) {
      updates['account_no'] =
          accountNo.trim().isEmpty ? null : accountNo.trim();
    }
    if (updates.isEmpty) return;
    final before = await bank(id);
    if (before == null) return;
    final dev = await _deviceId();
    final now = DateTime.now().toUtc();
    await _db.transaction((txn) async {
      await txn.update('banks', updates, where: 'id = ?', whereArgs: [id]);
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'bank',
            entityId: id,
            action: ChangeAction.edit,
            originalData: jsonEncode(before.toMap()),
            newData: jsonEncode(updates),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  Future<void> archiveBank(String id, {String? note}) async {
    final b = await bank(id);
    if (b == null) return;
    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'banks',
        {'is_archived': 1, 'archived_at': now.toIso8601String()},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'bank',
            entityId: id,
            action: ChangeAction.archive,
            originalData: jsonEncode(b.toMap()),
            note: note,
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  Future<void> unarchiveBank(String id) async {
    final b = await bank(id);
    if (b == null) return;
    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'banks',
        {'is_archived': 0, 'archived_at': null},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'bank',
            entityId: id,
            action: ChangeAction.unarchive,
            originalData: jsonEncode(b.toMap()),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  /// Delete a bank IFF it has never been used in a journal entry. Otherwise
  /// throws — historical balances must keep referring to a real account.
  /// Most callers should use [archiveBank] instead so the audit trail stays
  /// intact.
  Future<void> deleteBank(String id) async {
    final used = await _db.rawQuery(
      'SELECT 1 FROM journal_entries WHERE account_id = ? LIMIT 1',
      [id],
    );
    if (used.isNotEmpty) {
      throw StateError(
          'Bank/wallet $id is referenced by journal entries and cannot be deleted. Archive it instead.');
    }
    await _db.delete('banks', where: 'id = ?', whereArgs: [id]);
  }

  // ---- Counter Entities ----

  Future<CounterEntity> createCounterEntity({
    required String name,
    required CounterEntityType type,
    double amount = 0,
  }) async {
    final e = CounterEntity(
      id: _uuid.v4(),
      name: name.trim(),
      type: type,
      amount: amount,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('counter_entities', e.toMap());
    return e;
  }

  Future<List<CounterEntity>> counterEntities() async {
    final rows =
        await _db.query('counter_entities', orderBy: 'name COLLATE NOCASE');
    return rows.map(CounterEntity.fromMap).toList();
  }

  Future<void> updateCounterEntityAmount(String id, double amount) async {
    await _db.update('counter_entities', {'amount': amount},
        where: 'id = ?', whereArgs: [id]);
  }

  // ---- Material Inventory ----

  /// New (post-quantity-removal): the form collects only price + memo, so
  /// inventory rows record `quantity = 1`, `rate = price`, `unit = lump`.
  /// Callers that still need the legacy quantity/rate flow can pass them
  /// explicitly.
  Future<MaterialItem> logMaterialPurchase({
    required String projectId,
    required String supplierId,
    String? transactionId,
    required String materialType,
    required double price,
  }) async {
    final item = MaterialItem(
      id: _uuid.v4(),
      projectId: projectId,
      supplierId: supplierId,
      transactionId: transactionId,
      materialType: materialType,
      unit: MaterialUnit.lump,
      quantity: 1,
      rate: price,
      totalCost: price,
      txnType: MaterialTxnType.purchase,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('material_inventory', item.toMap());
    return item;
  }

  // ---- Material Types (user-defined categories) ----

  /// All material categories, built-ins first then alphabetical for the rest.
  /// `sort_order` lets the seeded built-ins (Brick, Cement, Sarya, Finishing,
  /// Other) keep their original order; user rows fall back to insertion time.
  Future<List<MaterialTypeDef>> materialTypes() async {
    final rows = await _db.query(
      'material_types',
      orderBy: 'is_builtin DESC, sort_order ASC, name ASC',
    );
    return rows.map(MaterialTypeDef.fromMap).toList();
  }

  /// Adds a new user-defined material type. Trims whitespace and rejects
  /// duplicates (case-insensitive) to keep the dropdown clean. Returns the
  /// row, or `null` if [name] was empty.
  ///
  /// All procurement metadata is optional — the caller can record only the
  /// name and edit the rest later from the type's detail screen.
  ///
  /// Throws if a row with the same name already exists.
  Future<MaterialTypeDef?> addMaterialType(
    String name, {
    UomType? uomType,
    String? uom,
    double? coverageRate,
    MaterialDims? dims,
  }) async {
    final clean = name.trim();
    if (clean.isEmpty) return null;

    final existing = await _db.query(
      'material_types',
      where: 'LOWER(name) = LOWER(?)',
      whereArgs: [clean],
      limit: 1,
    );
    if (existing.isNotEmpty) {
      throw StateError('A material type named "$clean" already exists.');
    }

    final row = MaterialTypeDef(
      id: _uuid.v4(),
      name: clean,
      isBuiltin: false,
      // Pushes user-added rows after the built-ins and any earlier customs.
      sortOrder: 1000 + DateTime.now().millisecondsSinceEpoch ~/ 1000,
      uomType: uomType,
      uom: uom,
      coverageRate: coverageRate,
      dims: dims,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('material_types', row.toMap());
    return row;
  }

  /// Updates editable fields on an existing material type. Built-ins can be
  /// renamed and have their procurement metadata edited, but they cannot be
  /// deleted (so historical inventory rows always resolve to a label).
  ///
  /// Pass `null` for any field to clear it (e.g. removing a coverage rate).
  /// Pass nothing (omit the named arg) to leave it unchanged.
  Future<void> updateMaterialType(
    String id, {
    Object? name = _unset,
    Object? uomType = _unset,
    Object? uom = _unset,
    Object? coverageRate = _unset,
    Object? dims = _unset,
  }) async {
    final patch = <String, Object?>{};
    if (!identical(name, _unset)) {
      final cleaned = (name as String?)?.trim();
      if (cleaned == null || cleaned.isEmpty) return;
      patch['name'] = cleaned;
    }
    if (!identical(uomType, _unset)) {
      patch['uom_typ'] = (uomType as UomType?)?.db;
    }
    if (!identical(uom, _unset)) {
      final cleaned = (uom as String?)?.trim();
      patch['uom'] = (cleaned == null || cleaned.isEmpty) ? null : cleaned;
    }
    if (!identical(coverageRate, _unset)) {
      patch['cov_rate'] = coverageRate as double?;
    }
    if (!identical(dims, _unset)) {
      final d = dims as MaterialDims?;
      patch['dims'] = (d == null || d.isEmpty) ? null : jsonEncode(d.toJson());
    }
    if (patch.isEmpty) return;
    await _db
        .update('material_types', patch, where: 'id = ?', whereArgs: [id]);
  }

  /// Backwards-compatible helper for callers that only need to rename.
  Future<void> renameMaterialType(String id, String newName) =>
      updateMaterialType(id, name: newName);

  /// Deletes a material type. Every row is freely deletable now —
  /// historical material_inventory rows store the type name as a free-form
  /// string, so removing the catalog row only hides the option from the
  /// Buy Material dropdown going forward.
  Future<bool> deleteMaterialType(String id) async {
    final n = await _db.delete(
      'material_types',
      where: 'id = ?',
      whereArgs: [id],
    );
    return n > 0;
  }

  Future<List<MaterialItem>> materialInventory({String? projectId}) async {
    final rows = await _db.query(
      'material_inventory',
      where: projectId != null ? 'project_id = ?' : null,
      whereArgs: projectId != null ? [projectId] : null,
      orderBy: 'created_at DESC',
    );
    return rows.map(MaterialItem.fromMap).toList();
  }

  // ---- Settings ----

  Future<String?> getSetting(String key) async {
    final rows = await _db.query('app_settings',
        where: 'key = ?', whereArgs: [key], limit: 1);
    return rows.isEmpty ? null : rows.first['value'] as String?;
  }

  Future<void> setSetting(String key, String? value) async {
    await _db.insert(
      'app_settings',
      {'key': key, 'value': value},
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  // ---- Change Log ----

  Future<List<ChangeLog>> changeLog({String? entityType, int? limit}) async {
    final rows = await _db.query(
      'change_log',
      where: entityType == null ? null : 'entity_type = ?',
      whereArgs: entityType == null ? null : [entityType],
      orderBy: 'timestamp DESC',
      limit: limit,
    );
    return rows.map(ChangeLog.fromMap).toList();
  }

  Future<void> logChange({
    required String entityType,
    required String entityId,
    required ChangeAction action,
    Map<String, Object?>? originalData,
    Map<String, Object?>? newData,
    String? note,
  }) async {
    await _db.insert(
        'change_log',
        ChangeLog(
          id: _uuid.v4(),
          entityType: entityType,
          entityId: entityId,
          action: action,
          originalData:
              originalData == null ? null : jsonEncode(originalData),
          newData: newData == null ? null : jsonEncode(newData),
          note: note,
          deviceId: await _deviceId(),
          timestamp: DateTime.now().toUtc(),
        ).toMap());
  }
}

/// Internal struct for [EntityRepository._projectLedgerBalance]. Exists
/// purely to bundle the two gating numbers the archive guard needs.
class _ProjectLedgerBalance {
  final double supplierPayables;
  final double ledgerNet;
  const _ProjectLedgerBalance({
    required this.supplierPayables,
    required this.ledgerNet,
  });

  /// Gate fails when either side has not been zeroed out (1 paisa
  /// tolerance to absorb floating-point noise from divisions).
  bool get isOutOfBalance =>
      supplierPayables.abs() >= 0.01 || ledgerNet.abs() >= 0.01;
}

/// Thrown when an attempt is made to archive a project whose ledger has
/// not been fully reconciled. Carries both the outstanding supplier
/// payable balance and the project ledger net so the UI can tell the
/// user what's wrong.
class ReconciliationException implements Exception {
  final String projectId;
  final double outstandingPayables;
  final double netLedger;
  const ReconciliationException({
    required this.projectId,
    required this.outstandingPayables,
    this.netLedger = 0,
  });
  @override
  String toString() => 'ReconciliationException(project=$projectId, '
      'outstandingPayables=$outstandingPayables, netLedger=$netLedger)';
}

/// Thrown when an attempt is made to archive a supplier whose payable
/// balance is not zero. The UI catches this and tells the user how much
/// is still owed (or owed-to-us).
class SupplierNotSettledException implements Exception {
  final String supplierId;
  final double outstandingBalance;
  const SupplierNotSettledException({
    required this.supplierId,
    required this.outstandingBalance,
  });
  @override
  String toString() => 'SupplierNotSettledException(supplier=$supplierId, '
      'balance=$outstandingBalance)';
}
